import React from 'react'
import PropTypes from 'prop-types'

const Datenschutzerklaerung = () => {
    const domain = window.domainName.name.split('.')[window.domainName.name.split('.').length - 1]

return (
  <div className="container">
            <h1>Datenschutzerklärung</h1>

<p>Der Schutz und die Sicherheit von persönlichen Daten hat bei uns eine hohe Priorität. Nachfolgend werden Sie darüber informiert, welche Art von Daten erfasst und zu welchem Zweck sie erhoben werden:</p>
<h2>1. Datenübermittlung / Datenprotokollierung</h2><p>Beim Besuch dieser Seite verzeichnet der Web-Server automatisch Log-Files, die keiner bestimmten Person zugeordnet werden können. Diese Daten beinhalten z. B. den Browsertyp und -version, verwendetes Betriebssystem, Referrer URL (die zuvor besuchte Seite), IP-Adresse des anfragenden Rechners, Zugriffsdatum und -uhrzeit der Serveranfrage und die Dateianfrage des Client (Dateiname und URL). Diese Daten werden nur zum Zweck der statistischen Auswertung gesammelt. Eine Weitergabe an Dritte, zu kommerziellen oder nichtkommerziellen Zwecken, findet nicht statt.</p>
<h2>2. Nutzung persönlicher Daten</h2><p>Persönliche Daten werden nur erhoben oder verarbeitet, wenn Sie diese Angaben freiwillig, z.B. im Rahmen einer Anfrage mitteilen. Sofern keine erforderlichen Gründe im Zusammenhang mit einer Geschäftsabwicklung bestehen, können Sie jederzeit die zuvor erteilte Genehmigung Ihrer persönlichen Datenspeicherung mit sofortiger Wirkung schriftlich (z.B. per E-Mail) widerrufen. Ihre Daten werden nicht an Dritte weitergeben, es sei denn, eine Weitergabe ist aufgrund gesetzlicher Vorschriften erforderlich.</p>
<h2>3. Auskunft, Änderung und Löschung Ihrer Daten</h2><p>Gemäss geltendem Recht können Sie jederzeit bei uns schriftlich nachfragen, ob und welche personenbezogenen Daten bei uns über Sie gespeichert sind. Eine entsprechende Mitteilung hierzu erhalten Sie umgehend.</p>
<h2>4. Sicherheit Ihrer Daten</h2><p>Ihre uns zur Verfügung gestellten persönlichen Daten werden durch Ergreifung aller technischen sowie organisatorischen Sicherheitsmassnahmen so gesichert, dass sie für den Zugriff unberechtigter Dritter unzugänglich sind. Bei Versendung von sehr sensiblen Daten oder Informationen ist es empfehlenswert, den Postweg zu nutzen, da eine vollständige Datensicherheit per E-Mail nicht gewährleistet werden kann.</p>
<h2>5. Hinweis zu Google Analytics</h2><p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. („Google“).  Google Analytics verwendet sog. „Cookies“, d. h. Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglicht. Die durch den Cookie erzeugten Informationen über Ihre Benutzung diese Website (einschliesslich Ihrer IP-Adresse) wird an einen Server von Google in den USA übertragen und dort gespeichert. Google wird diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten für die Websitebetreiber zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen zu erbringen. Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten der Google in Verbindung bringen. Sie können die Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website voll umfänglich nutzen können. Durch die Nutzung dieser Website erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.</p>
<h2>6. Cookies</h2><p>Auf einigen unserer Seiten verwenden wir sog. "Session-Cookies", um Ihnen die Nutzung unserer Webseiten zu erleichtern. Dabei handelt es sich um kleine Textdateien, die nur für die Dauer Ihres Besuchs unserer Webseite auf Ihrer Festplatte hinterlegt und abhängig von der Einstellung Ihres Browser-Programms beim Beenden des Browsers wieder gelöscht werden. Diese Cookies rufen keine auf Ihrer Festplatte über Sie gespeicherten Informationen ab und beeinträchtigen nicht Ihren PC oder ihre Dateien. Die meisten Browser sind so eingestellt, dass sie Cookies automatisch akzeptieren. Sie können das Speichern von Cookies jedoch deaktivieren oder ihren Browser so einstellen, dass er Sie auf die Sendung von Cookies hinweist.</p>
<h2>7. Änderungen dieser Datenschutzbestimmungen</h2><p>Wir werden diese Richtlinien zum Schutz Ihrer persönlichen Daten von Zeit zu Zeit aktualisieren. Sie sollten sich diese Richtlinien gelegentlich ansehen, um auf dem Laufenden darüber zu bleiben, wie wir Ihre Daten schützen und die Inhalte unserer Website stetig verbessern. Sollten wir wesentliche Änderungen bei der Sammlung, der Nutzung und/oder der Weitergabe der uns von Ihnen zur Verfügung gestellten personenbezogenen Daten vornehmen, werden wir Sie durch einen eindeutigen und gut sichtbaren Hinweis auf der Website darauf aufmerksam machen. Mit der Nutzung der Webseite erklären Sie sich mit den Bedingungen dieser Richtlinien zum Schutz persönlicher Daten einverstanden.</p>
<h2>8. Datenschutzerklärung für die Nutzung von Fullstory</h2>
<p>Unsere Webseite nutzt die Dienstleistungen von Fullstory, ein Webseitenanalysedienst der Fullstory Inc., 818 Marietta Street, Atlanta, GA 30318, USA. Fullstory zeichnet das Nutzerverhalten auf unserer Webseite auf. Die Aufzeichnungen von Besuchersitzungen ermöglichen es dem Betreiber der Seite, diese zu analysieren und anschließend die Webseitenerfahrung für Besucher zu verbessern. Fullstory speichert und sammelt Daten in anonymisierter Form mithilfe von Cookies. Das Tracking (d.h. die Erfassung der durch das Cookie erzeugten und auf die Nutzung der Website bezogenen Daten) kann jederzeit deaktiviert werden. Bitte folgen Sie hierzu der Anleitung auf <a href="https://www.fullstory.com/optout" target="_blank">www.fullstory.com/optout.</a></p>
<h2>9. Einsatz von Google Remarketing</h2>
<p>Diese Website verwendet die Remarketing-Funktion der Google Inc. („Google“). Diese Funktion dient dazu, Besuchern der Website im Rahmen des Google-Werbenetzwerks interessenbezogene Werbeanzeigen zu präsentieren. Der Browser des Websitebesuchers speichert sog. „Cookies“, Textdateien, die auf Ihrem Computer gespeichert werden und die es ermöglichen, den Besucher wiederzuerkennen, wenn dieser Websites aufruft, die dem Werbenetzwerk von Google angehören. Auf diesen Seiten können dem Besucher dann Werbeanzeigen präsentiert werden, die sich auf Inhalte beziehen, die der Besucher zuvor auf Websites aufgerufen hat, die die Remarketing Funktion von Google verwenden. Nach eigenen Angaben erhebt Google bei diesem Vorgang keine personenbezogenen Daten. Sollten Sie die Funktion Remarketing von Google dennoch nicht wünschen, können Sie diese grundsätzlich deaktivieren, indem Sie die entsprechenden Einstellungen unter <a href="http://www.google.com/settings/ads" target="_blank">www.google.com/settings/ads</a> vornehmen. Alternativ können Sie den Einsatz von Cookies für interessenbezogene Werbung über die Werbenetzwerkinitiative deaktivieren, indem Sie den Anweisungen unter <a href="http://www.networkadvertising.org/managing/opt_out.asp" target="_blank">www.networkadvertising.org/managing/opt_out.asp</a>
folgen.</p>
<h2>10. Nutzung von Facebook Remarketing (Pixel)</h2>
<p>Diese Website verwendet die Remarketing-Funktion „Custom Audiences“ der Facebook Inc. („Facebook“). Diese Funktion dient dazu, Besuchern dieser Webseite im Rahmen des Besuchs des sozialen Netzwerkes Facebook interessenbezogene Werbeanzeigen („Facebook-Ads“) zu präsentieren. Hierzu wurde auf dieser Website das Remarketing-Tag von Facebook implementiert. Über dieses Tag wird beim Besuch der Webseite eine direkte Verbindung zu den Facebook-Servern hergestellt. Dabei wird an den Facebook-Server übermittelt, dass Sie diese Website besucht haben und Facebook ordnet diese Information Ihrem persönlichen Facebook-Benutzerkonto zu. Nähere Informationen zur Erhebung und Nutzung der Daten durch Facebook sowie über Ihre diesbezüglichen Rechte und Möglichkeiten zum Schutz Ihrer Privatsphäre finden Sie in den Datenschutzhinweisen von Facebook unter <a href="https://www.facebook.com/about/privacy/" target="_blank">www.facebook.com/about/privacy/</a>. Alternativ können Sie die Remarketing-Funktion „Custom Audiences“ unter <a href="https://www.facebook.com/settings/?tab=ads#_=_" target="_blank">www.facebook.com/settings/?tab=ads#_=_</a> deaktivieren. Hierfür müssen Sie bei Facebook angemeldet sein.</p>
<h2>11. Nutzung von Snap-Pixel</h2>
<p>Diese Website verwendet die Funktion „Snap Pixel“ der Snap Inc. (Snapchat). Diese Funktion dient dazu, Besuchern dieser Webseite im Rahmen des Besuchs des Onlinedienstes Snapchat interessenbezogene Werbeanzeigen zu präsentieren. Hierzu wurde auf dieser Website das Snap-Pixel-Tag von Snapchat implementiert. Über dieses Tag wird beim Besuch der Webseite eine direkte Verbindung zu den Snapchat-Servern hergestellt. Dabei wird an den Snapchat-Server übermittelt, dass Sie diese Website besucht haben und Snapchat ordnet diese Information Ihrem persönlichen Snapchat-Benutzerkonto zu. Mit Hilfe des Snap-Pixels möchten wir ebenfalls sicherstellen, dass unsere Snapchat-Ads dem potentiellen Interesse der Nutzer entsprechen und nicht belästigend wirken.
Nähere Informationen zur Erhebung und Nutzung der Daten durch Snapchat sowie über Ihre diesbezüglichen Rechte und Möglichkeiten zum Schutz Ihrer Privatsphäre finden Sie in den Datenschutzhinweisen von Snapchat unter <a href="https://www.snap.com/en-US/privacy/privacy-center" target="_blank">www.snap.com/en-US/privacy/privacy-center</a>.
</p>

<h2>12. AgileCRM</h2>
<p>Unsere Webseite nutzt Funktionen des CRM Systems Agile CRM. Anbieter ist die Agile CRM Inc., Hyderabad, Indien. Bei jedem Abruf einer unserer Seiten, die Funktionen von Agile CRM enthält, wird eine Verbindung zu Servern von Agile CRM hergestellt. Eine Speicherung von personenbezogenen Daten erfolgt dabei nach unserer Kenntnis nicht. Insbesondere werden keine IP-Adressen gespeichert oder das Nutzungsverhalten ausgewertet.<br />
Weitere Information zum Datenschutz finden Sie in der Datenschutzerklärung von Agile CRM unter <a href="https://www.agilecrm.com/privacy-policy" target="_blank">https://www.agilecrm.com/privacy-policy</a></p>

<h2>13. Verwendung von Facebook-Connect (Login mit Facebook-Konto)</h2>
<p>Wir bieten Ihnen die Möglichkeit sich für unseren Dienst mit Facebook-Connect anzumelden. Eine zusätzliche Registrierung ist somit nicht möglich. Zur Anmeldung werden Sie auf die Seite von Facebook weitergeleitet, wo Sie sich mit ihren Nutzungsdaten anmelden können. Hierdurch werden ihre Facebook-Profil und unser Dienst verknüpft. Durch die Verknüpfung erhalten wir automatisch von der Facebook Inc. Folgende Informationen werden an uns übermittelt:<br /><br />

Wir nutzen von diesen Daten ausschliesslich Ihren Namen und Ihre E-Mail-Adresse. Diese Informationen sind für den Vertragsschluss zwingend erforderlich, um sie identifizieren zu können.<br /><br />

Weitere Informationen zu Facebook-Connect und den Privatsphäre-Einstellungen entnehmen Sie bitte den Datenschutzhinweisen und den Nutzungsbedingungen der Facebook Inc.</p>

<p>Bei Fragen zu diesen Datenschutzbestimmungen wenden Sie sich bitte über unsere <a href="/kontakt">Kontakt-Seite</a> an uns.</p>
</div>
)
}


Datenschutzerklaerung.propTypes = {}
Datenschutzerklaerung.defaultProps = {}

export default Datenschutzerklaerung