export const LOAD_DEVICES_SUCCESS = 'LOAD_DEVICES_SUCCESS';
export const LOAD_DEVICES_FOR_SELL_SUCCESS = 'LOAD_DEVICES_FOR_SELL_SUCCESS';
export const LOAD_MODELS_SUCCESS = 'LOAD_MODELS_SUCCESS';
export const SET_FILTER_OPTIONS_SUCCESS = 'SET_FILTER_OPTIONS_SUCCESS';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const RETURN_SEARCH_RESULTS_TO_PREV_ROUTE = 'RETURN_SEARCH_RESULTS_TO_PREV_ROUTE';
